### ISSUE TITLE
how to build this on linux??

### ISSUE THREAD

**Issue by abcfy2** [ibell/coolprop#107]
I use `pip install coolprop` on linux,but it's failed!
- coolprop version: 4.0
- OS: linuxmint 15
- python version: 2.7 & 3.3

here is log:

```
------------------------------------------------------------
/usr/bin/pip run on Thu Jan 23 13:41:52 2014
Downloading/unpacking coolprop

  Running setup.py egg_info for package coolprop

    usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]

               [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]

               [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]

               [-c name=value] [--help]

               <command> [<args>]



    The most commonly used git commands are:

       add        Add file contents to the index

       bisect     Find by binary search the change that introduced a bug

       branch     List, create, or delete branches

       checkout   Checkout a branch or paths to the working tree

       clone      Clone a repository into a new directory

       commit     Record changes to the repository

       diff       Show changes between commits, commit and working tree, etc

       fetch      Download objects and refs from another repository

       grep       Print lines matching a pattern

       init       Create an empty git repository or reinitialize an existing one

       log        Show commit logs

       merge      Join two or more development histories together

       mv         Move or rename a file, a directory, or a symlink

       pull       Fetch from and merge with another repository or a local branch

       push       Update remote refs along with associated objects

       rebase     Forward-port local commits to the updated upstream head

       reset      Reset current HEAD to the specified state

       rm         Remove files from the working tree and from the index

       show       Show various types of objects

       status     Show the working tree status

       tag        Create, list, delete or verify a tag object signed with GPG



    See 'git help <command>' for more information on a specific command.

    running egg_info
    writing pip-egg-info/CoolProp.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/CoolProp.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/CoolProp.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found


    reading manifest file 'pip-egg-info/CoolProp.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/CoolProp.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-root/coolprop has version 4.0.0, which satisfies requirement coolprop
Installing collected packages: coolprop

  Running setup.py install for coolprop

    Running command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/coolprop/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_r7WyY-record/install-record.txt --single-version-externally-managed
    usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]

               [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]

               [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]

               [-c name=value] [--help]

               <command> [<args>]



    The most commonly used git commands are:

       add        Add file contents to the index

       bisect     Find by binary search the change that introduced a bug

       branch     List, create, or delete branches

       checkout   Checkout a branch or paths to the working tree

       clone      Clone a repository into a new directory

       commit     Record changes to the repository

       diff       Show changes between commits, commit and working tree, etc

       fetch      Download objects and refs from another repository

       grep       Print lines matching a pattern

       init       Create an empty git repository or reinitialize an existing one

       log        Show commit logs

       merge      Join two or more development histories together

       mv         Move or rename a file, a directory, or a symlink

       pull       Fetch from and merge with another repository or a local branch

       push       Update remote refs along with associated objects

       rebase     Forward-port local commits to the updated upstream head

       reset      Reset current HEAD to the specified state

       rm         Remove files from the working tree and from the index

       show       Show various types of objects

       status     Show the working tree status

       tag        Create, list, delete or verify a tag object signed with GPG



    See 'git help <command>' for more information on a specific command.

    running install
    running build
    running build_py
    copying CoolProp/__init__.py -> build/lib.linux-x86_64-2.7/CoolProp
    running build_ext
    cythoning CoolProp/CoolProp.pyx to build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

        """

        A convenience function to convert a double value back to the units that

        are desired by the user

        """

        # Convert to a byte-string

        cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

                                                   ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:57:48: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

        A convenience function to convert a double value back to the units that

        are desired by the user

        """

        # Convert to a byte-string

        cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

        cdef bytes _desired_units = desired_units if bytes_or_str is bytes else desired_units.encode('ascii')

                                                 ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:58:46: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

    cdef _convert_to_default_units(bytes_or_str parameter_type, object parameter):

        """

        A convenience function to convert a quantities instance to the default

        units required for CoolProp

        """

        cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

                                                   ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:75:48: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

        cdef bytes _ReferenceFluid = ReferenceFluid.encode('ascii')

        _conformal_Trho(_Fluid, _ReferenceFluid, T, rho, &T0, &rho0)

        return T0,rho0



    cpdef rhosatL_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                                 ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:754:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

    cpdef rhosatL_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

        return _rhosatL_anc(_Fluid,T)



    cpdef rhosatV_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                                 ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:758:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

    cpdef rhosatV_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

        return _rhosatV_anc(_Fluid,T)



    cpdef psatL_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                                 ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:762:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



    Error compiling Cython file:

    ------------------------------------------------------------

    ...

    cpdef psatL_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

        return _psatL_anc(_Fluid,T)



    cpdef psatV_anc(bytes_or_str Fluid, double T):

        cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                                 ^

    ------------------------------------------------------------



    CoolProp/CoolProp.pyx:766:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.

    building 'CoolProp.CoolProp' extension

    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -ICoolPropSource -I/usr/include/python2.7 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.o

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

    build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    Complete output from command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/coolprop/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_r7WyY-record/install-record.txt --single-version-externally-managed:

    usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]

           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]

           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]

           [-c name=value] [--help]

           <command> [<args>]



The most commonly used git commands are:

   add        Add file contents to the index

   bisect     Find by binary search the change that introduced a bug

   branch     List, create, or delete branches

   checkout   Checkout a branch or paths to the working tree

   clone      Clone a repository into a new directory

   commit     Record changes to the repository

   diff       Show changes between commits, commit and working tree, etc

   fetch      Download objects and refs from another repository

   grep       Print lines matching a pattern

   init       Create an empty git repository or reinitialize an existing one

   log        Show commit logs

   merge      Join two or more development histories together

   mv         Move or rename a file, a directory, or a symlink

   pull       Fetch from and merge with another repository or a local branch

   push       Update remote refs along with associated objects

   rebase     Forward-port local commits to the updated upstream head

   reset      Reset current HEAD to the specified state

   rm         Remove files from the working tree and from the index

   show       Show various types of objects

   status     Show the working tree status

   tag        Create, list, delete or verify a tag object signed with GPG



See 'git help <command>' for more information on a specific command.

running install

running build

running build_py

copying CoolProp/__init__.py -> build/lib.linux-x86_64-2.7/CoolProp

running build_ext

cythoning CoolProp/CoolProp.pyx to build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp



Error compiling Cython file:

------------------------------------------------------------

...

    """

    A convenience function to convert a double value back to the units that

    are desired by the user

    """

    # Convert to a byte-string

    cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

                                               ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:57:48: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

    A convenience function to convert a double value back to the units that

    are desired by the user

    """

    # Convert to a byte-string

    cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

    cdef bytes _desired_units = desired_units if bytes_or_str is bytes else desired_units.encode('ascii')

                                             ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:58:46: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

cdef _convert_to_default_units(bytes_or_str parameter_type, object parameter):

    """

    A convenience function to convert a quantities instance to the default

    units required for CoolProp

    """

    cdef bytes _parameter_type = parameter_type if bytes_or_str is bytes else parameter_type.encode('ascii')

                                               ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:75:48: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

    cdef bytes _ReferenceFluid = ReferenceFluid.encode('ascii')

    _conformal_Trho(_Fluid, _ReferenceFluid, T, rho, &T0, &rho0)

    return T0,rho0



cpdef rhosatL_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                             ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:754:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

cpdef rhosatL_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

    return _rhosatL_anc(_Fluid,T)



cpdef rhosatV_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                             ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:758:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

cpdef rhosatV_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

    return _rhosatV_anc(_Fluid,T)



cpdef psatL_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                             ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:762:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.



Error compiling Cython file:

------------------------------------------------------------

...

cpdef psatL_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

    return _psatL_anc(_Fluid,T)



cpdef psatV_anc(bytes_or_str Fluid, double T):

    cdef bytes _Fluid = Fluid if bytes_or_str is bytes else Fluid.encode('ascii')

                             ^

------------------------------------------------------------



CoolProp/CoolProp.pyx:766:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.

building 'CoolProp.CoolProp' extension

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -ICoolPropSource -I/usr/include/python2.7 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.o

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------

Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/coolprop/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_r7WyY-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/coolprop

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 271, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1185, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 592, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/coolprop/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_r7WyY-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/coolprop
```

**Comment by ibell** [comment]
This is due to a regression in Cython.  I'm going to fix this, hopefully
permanently.  Watch this space

**Comment by ibell** [comment]
Ok, problem fixed.  You will need to build from source, which is as easy as
downloading the zip from
https://github.com/ibell/coolprop/archive/master.zip , unzip, open a
terminal, type `python setup.py install`

Regards,
Ian

**Comment by abcfy2** [comment]
But in `install` step, it also raise an error.

```
# python setup.py install
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]

The most commonly used git commands are:
   add        Add file contents to the index
   bisect     Find by binary search the change that introduced a bug
   branch     List, create, or delete branches
   checkout   Checkout a branch or paths to the working tree
   clone      Clone a repository into a new directory
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   fetch      Download objects and refs from another repository
   grep       Print lines matching a pattern
   init       Create an empty git repository or reinitialize an existing one
   log        Show commit logs
   merge      Join two or more development histories together
   mv         Move or rename a file, a directory, or a symlink
   pull       Fetch from and merge with another repository or a local branch
   push       Update remote refs along with associated objects
   rebase     Forward-port local commits to the updated upstream head
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index
   show       Show various types of objects
   status     Show the working tree status
   tag        Create, list, delete or verify a tag object signed with GPG

See 'git help <command>' for more information on a specific command.
running install
running build
running build_py
copying CoolProp/__init__.py -> build/lib.linux-x86_64-2.7/CoolProp
running build_ext
skipping 'build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp' Cython extension (up-to-date)
skipping 'build/temp.linux-x86_64-2.7/pyrex/CoolProp/param_constants.cpp' Cython extension (up-to-date)
skipping 'build/temp.linux-x86_64-2.7/pyrex/CoolProp/phase_constants.cpp' Cython extension (up-to-date)
skipping 'build/temp.linux-x86_64-2.7/pyrex/CoolProp/unit_systems_constants.cpp' Cython extension (up-to-date)
running install_lib
copying build/lib.linux-x86_64-2.7/CoolProp/__init__.py -> /usr/local/lib/python2.7/dist-packages/CoolProp
byte-compiling /usr/local/lib/python2.7/dist-packages/CoolProp/__init__.py to __init__.pyc
  File "/usr/local/lib/python2.7/dist-packages/CoolProp/__init__.py", line 3
    __gitrevision__ ="
                     ^
SyntaxError: EOL while scanning string literal

running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/CoolProp-4.0.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/CoolProp-4.0.0.egg-info
```

**Comment by ibell** [comment]
Interesting.  Thats a new one I haven't seen before.  What are the
contents of the **init**.py file it complains about?

**Comment by ibell** [comment]
Try again now?  I've pushed some changes that might fix your issues.
Hopefully it should work.  I just built on linux with py2.7

**Comment by abcfy2** [comment]
Maybe it's fixed.
I'm not use my own PC now. I use another PC with LinuxDeepin 2013 for testing. It's also based on Ubuntu 13.04.
I will try it on my own PC tomorrow.
Thank you.

**Comment by ibell** [comment]
3.3 looks like it still has some issues with the build.  Let me fix those
too.  I'm doing a CoolProp development sprint today.

**Comment by abcfy2** [comment]
I just clone the latest project. When I enter the dir, it receives a waring:

```
warning: CRLF will be replaced by LF in CoolProp/Brine.cpp.                                                                                                                                   
The file will have its original line endings in your working directory.
```

On my own PC, I use zsh shell.

There is no other errors. It's fixed.

Thank you all for the hard work.

The last problem is that how can I call coolprop in JAVA ?

I move the CoolProp.so file to the same degree as the Example.java, but failed.

Could you write more doc about how to use coolprop on linux ?

**Comment by shabdaly** [comment]
I'm having the same problem trying to install this on Mac OSX. I tried following the steps above, but still couldn't get it installed. The archive file master.zip does not contain a setup.py file in the top directory. There is one in the dev subdirectory of the archive, but it's not clear if that is the one you meant?

**Comment by ibell** [comment]
Are you trying to install for python?  If so, cd wrappers/Python, then run
the setup.py script in that folder.

**Comment by shabdaly** [comment]
Thanks for the reply. Now it seems to be installed, but I when I try importing the module I get the same error appearing above:

```
File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/CoolProp/__init__.py", line 3
    __gitrevision__ ="
                     ^
SyntaxError: EOL while scanning string literal
```

**Comment by ibell** [comment]
I thought I fixed this problem.  Can you send me a copy of the full build
process?  Something has gone funny with the git revision parsing again it
seems.  Can you please also attach the file referenced in your last email?
I'm curious to see what it looks like.

**Comment by shabdaly** [comment]
I've put a log file and the requested file at the link below:
https://gist.github.com/shabdaly/8800694
It look as if there's a missing double quote. Not sure if it's just a matter of manually sticking one in, or does this originate somewhere else?

**Comment by shabdaly** [comment]
Manually adding in a second double quote seems to have fixed it for me for now.

**Comment by ibell** [comment]
There should be a git revision in that broken string.  I'll have to do some
more debugging to figure out why that isn't the case.

**Comment by ibell** [comment]
Can you try again please?  I made some changes to the build script.  Thanks

**Comment by shabdaly** [comment]
I'm not sure which one you wanted to retry. I assume you've updated the file at the link https://github.com/ibell/coolprop/archive/master.zip
If so, it doesn't seem to be fixed. I get the same error I had before (missing quote).

```
File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/CoolProp/__init__.py", line 3
    __gitrevision__ ="
                     ^
SyntaxError: EOL while scanning string literal
```

**Comment by shabdaly** [comment]
Deleting the module and then trying to install using:

```
easy_install CoolProp
```

or:

```
easy_install -U CoolProp
```

didn't work either. In the first case I would get:

```
Searching for coolprop
Best match: CoolProp 4.0.0
Adding CoolProp 4.0.0 to easy-install.pth file

Using /Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages
Processing dependencies for coolprop
Finished processing dependencies for coolprop
```

But it didn't seem to be installed, so I tried using -U, but then I get the original error:

```
CoolProp/CoolProp.pyx:766:30: Cannot convert 'str' to 'bytes' implicitly. This is not portable.
build/temp.macosx-10.5-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:1:2: error: Do not use this file, it is the result of a failed Cython
      compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

Let me know if there are different steps you would like me to follow.

**Comment by ibell** [comment]
1. Do you have git installed?
2. Can you please give me the full output of when you try to run the
   setup.py file from the master zip file at the URL you note?  It should
   work...  Except that it doesn't

**Comment by shabdaly** [comment]
1. Yes, git is installed (but I'm not using it here).
2. The compilation processes completes successfully with no error messages. A copy of the terminal output is available here:
   https://gist.github.com/shabdaly/8849290
   The problem only appears when, in iPython I first import CoolProp:

```
In [1]: import CoolProp.CoolProp as CP
  File "/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/site-packages/CoolProp/__init__.py", line 3
    __gitrevision__ ="
                     ^
SyntaxError: EOL while scanning string literal
```

and it doesn't get imported.

But I just noticed that when I repeat the import command above, I don't get any error message and it gets imported (apparently) successfully.

**Comment by ibell** [comment]
Ok, I think I have fixed it.  Please give me the output of the build script
for you when building from the zip

**Comment by shabdaly** [comment]
Ok, it's fixed. The error message no longer appears when importing CoolProp.

As you requested, the output of the build script is available here:
https://gist.github.com/shabdaly/8867621

Cheers.

**Comment by ibell** [comment]
Good to hear.  Thanks for the report.
