### ISSUE TITLE
State class not working on python 3

### ISSUE THREAD

**Issue by spinnau** [ibell/coolprop#164]
In CoolProp version 4.1 the _State_-class is not working on python 3:

``` python
>>> from CoolProp.State import State
>>> State('Water', dict(T=400, P=100))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp.pyx", line 1055, in CoolProp.CoolProp.State.__init__ (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:34001)
  File "CoolProp.pyx", line 1195, in CoolProp.CoolProp.State.update (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:35536)
ValueError: CoolProp error: Non-numeric density obtained in density_TP with inputs T=0,p=100000,rho_guess=nan for fluid Water
```

This bug firstly occurs after the changesets 7599c77360287c3c0f3835b and 3c7e73c24b877936c0c918 (Fixed CoolProp.pyx).

There are also errors for _State_ class with Python 3 (python 3.3.4 / cython 0.19.2 and cython 0.20.1) in master. With Python 2.7 it works fine for 4.1 and master.

``` python
>>> from CoolProp.State import State
>>> State('Water', dict(T=400, P=100))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CoolProp.pyx", line 853, in CoolProp.CoolProp.State.__init__ (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:22619)
  File "stringsource", line 31, in string.to_py.__pyx_convert_string_to_py_ (build/temp.linux-x86_64-3.3/pyrex/CoolProp/CoolProp.cpp:31167)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf5 in position 9: ordinal not in range(128)
```

**Comment by ibell** [comment]
I'll take a look tomorrow!

**Comment by spinnau** [comment]
Thanks for the quick fix. _Master_ works on Python 2 and 3 now...
