### ISSUE TITLE
CoolProp install error with cython __init__()

### ISSUE THREAD

**Issue by d-e-t** [ibell/coolprop#208]
Trying to install the latest nightly build, I am running into the following error:

```
daniel@enet-solarceria1:~/python/coolprop/coolprop/wrappers/Python$ sudo python setup.py install
psutil was not found, it is used to kill the python completion server in Eclipse which keeps CoolProp from building sometimes.  psutils can be easy_install-ed
git version 1.7.10.4
git was found
git revision is ce553d41cfbd9046c04368905a9dbce0124ae9fa
Traceback (most recent call last):
  File "setup.py", line 208, in <module>
    **common_args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 87, in __init__
    **kw)
TypeError: unbound method __init__() must be called with Extension instance as first argument (got Extension instance instead)
```

cython was pip installed and is the latest version.  psutil is latest debian.  Using python 2.7 and Debian wheezy 3.2.0-4-amd64

Afterwards pip install CoolProp also fails with the same error.

**Comment by ibell** [comment]
Have you had success before?

**Comment by d-e-t** [comment]
Yes, I had pip installed it before, but was trying to get the latest version to use your P,S lookup fixes.

**Comment by d-e-t** [comment]
...ended up doing a dist-upgrade, and now got the latest version working.
