### ISSUE TITLE
Temperature lookup for low pressure gas

### ISSUE THREAD

**Issue by d-e-t** [ibell/coolprop#210]
I'm having trouble getting Props to return a temperature given (P,D) for a low pressure expansion problem.  Here is a simple version that works fine with Air, but not with Nitrogen, Oxygen, etc.  Below are the errors from running with Nitrogen.

```
import CoolProp.CoolProp as CP

fluid = 'Nitrogen'
T_i   = 298. # [K]
P_i   = 100. # [Pa]
D_i   = CP.PropsSI('D','T',T_i,'P',P_i,fluid)  # Initial density
D_f   = D_i*1.8
P_f   = P_i*(D_f/D_i)                          # Isothermal expansion
T_f   = CP.PropsSI('T','P',P_f,'D',D_f,fluid)  # [K]

print('\n  Input: {:.0f} Pa, {:.3f} kg/m3'.format(P_i,D_i))
print('  Output: {:.0f} Pa, {:.3f} kg/m3'.format(P_f,D_f))
```

And the output:

```
Traceback (most recent call last):
  File "coolprop_density_lookup.py", line 15, in <module>
    T_f   = CP.PropsSI('T','P',P_f,'D',D_f,fluid)  # [K]
  File "CoolProp.pyx", line 360, in CoolProp.CoolProp.PropsSI (build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:12339)
  File "CoolProp.pyx", line 458, in CoolProp.CoolProp.PropsSI (build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:11734)
  File "CoolProp.pyx", line 356, in CoolProp.CoolProp.__PropsSI_err2 (build/temp.linux-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:11259)
ValueError: CoolProp error: Inputs in Brent [63.151000,126.192000] do not bracket the root.  Function values are [12339.783487,3395620.444715] :: inputs were:"T","P",1.7999999999999997e+02,"D",2.0351045741603484e-03,"Nitrogen"
```

**Comment by ibell** [comment]
Should be fixed in b43d5cdc3dcd896f2cae430c223d266dfb6bdfbe - pressure was below triple point pressure, and it was getting confused as a result.  It tried to do a saturation call.
