### ISSUE TITLE
Easy_install build mingw

### ISSUE THREAD

**Issue by nfette** [ibell/coolprop#219]
Hi, I'm trying to follow the installation option 2, easy_install CoolProp. First weird message was getting a "git not found" message followed by gcc failed with exit status 1. I didn't think it should need git to fetch from PyPi, but installed it just to see what happens.

Hm, maybe I found my problem already. Cython 0.20.1 is configured to use mingw32 in distutils.cfg. But I had a stand-alone mingw with gcc 4.8.1 first in the path. My python distro (Pythonxy) installs its own mingw32 with gcc 4.5.2. When I removed the first one from the path, the install worked, although with many compiler warnings of deprecated conversions etc.

So no problem, I guess, sorry.

**Comment by ibell** [comment]
Actually the git stuff is just warnings, so need to worry.

WIth regards to GCC on windows (MinGW), the whole situation is quite
confusing to follow.  But yes, it will try to use the first GCC on the
system path, which you rightly note.  Surprising that compilation didn't
work with 4.8.1, what sort of warnings do you get?  Does it end up
working?  GCC is quite pedantic about some things that are completely
normal and fine.

**Comment by nfette** [comment]
```
C:\Users\nfette>where git
C:\Program Files (x86)\Git\cmd\git.exe
C:\Users\nfette>set PATH=C:\MinGW\bin;%PATH%
C:\Users\nfette>where gcc
C:\MinGW\bin\gcc.exe
C:\MinGW32-xy\bin\gcc.exe
C:\Users\nfette>gcc --version
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

C:\Users\nfette>easy_install CoolProp
Searching for CoolProp
Reading https://pypi.python.org/simple/CoolProp/
Best match: CoolProp 4.2.0
Downloading https://pypi.python.org/packages/source/C/CoolProp/CoolProp-4.2.0.zi
p#md5=fca58e8f27cceb281ec8d9c57e426d0e
Processing CoolProp-4.2.0.zip
Writing c:\users\nfette\appdata\local\temp\easy_install-hstnin\CoolProp-4.2.0\se
tup.cfg
Running CoolProp-4.2.0\setup.py -q bdist_egg --dist-dir c:\users\nfette\appdata\
local\temp\easy_install-hstnin\CoolProp-4.2.0\egg-dist-tmp-08mpwp
git version 1.9.2.msysgit.0
git was found
fatal: Not a git repository (or any of the parent directories): .git
tried to update git revision, but it failed for some reason (building from zip f
ile?)
warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir>
<pattern1> <pattern2> ...

gcc: error: CreateProcess: No such file or directory
error: Setup script exited with error: command 'gcc' failed with exit status 1
```

Failure seems to be with CreateProcess; maybe I need to download source and build manually to figure out if that is a file or directory that should have been created.

**Comment by nfette** [comment]
This method gives more verbose output on its failure:

```
C:\Users\nfette>pip install CoolProp

... [lots of good progress]

running build_ext

cythoning CoolProp\CoolProp.pyx to build\temp.win32-2.7\Release\pyrex\CoolProp\C
oolProp.cpp

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

creating build\temp.win32-2.7\Release\pyrex

creating build\temp.win32-2.7\Release\pyrex\CoolProp

building 'CoolProp.CoolProp' extension

creating build\temp.win32-2.7\Release\build

creating build\temp.win32-2.7\Release\build\temp.win32-2.7

creating build\temp.win32-2.7\Release\build\temp.win32-2.7\release

creating build\temp.win32-2.7\Release\build\temp.win32-2.7\release\pyrex

creating build\temp.win32-2.7\Release\build\temp.win32-2.7\release\pyrex\coolpro
p

creating build\temp.win32-2.7\Release\coolpropsource

C:\MinGW\bin\gcc.exe -mdll -O -Wall -ICoolPropSource -IC:\Python27\include -IC:\
Python27\include -IC:\Python27\PC -c build\temp.win32-2.7\Release\pyrex\CoolProp
\CoolProp.cpp -o build\temp.win32-2.7\Release\build\temp.win32-2.7\release\pyrex
\coolprop\coolprop.o

gcc: error: CreateProcess: No such file or directory

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\use
rs\\nfette\\appdata\\local\\temp\\pip_build_nfette\\CoolProp\\setup.py';exec(com
pile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __f
ile__, 'exec'))" install --record c:\users\nfette\appdata\local\temp\pip-dnjq4u-
record\install-record.txt --single-version-externally-managed --compile failed w
ith error code 1 in c:\users\nfette\appdata\local\temp\pip_build_nfette\CoolProp

Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 280, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python27\lib\site-packages\pip\req.py", line 1380, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python27\lib\site-packages\pip\req.py", line 699, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\nfette\\appdata\\local\\temp\\pip_build_nfette\\CoolProp\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\nfette\appdata\local\temp\pip-dnjq4u-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\nfette\appdata\local\temp\pip_build_nfette\CoolProp
```

**Comment by ibell** [comment]
I think you really want to be using the mingw32-xy version of GCC.  I have
been running into similar problems with GCC before.  And it seems like for
64-bit, the only working compiler on windows for now is MSVC (
https://github.com/cython/cython/wiki/64BitCythonExtensionsOnWindows).

**Comment by ibell** [comment]
Any luck? Can we close this issue?
