### ISSUE TITLE
problem trying to install via pip

### ISSUE THREAD

**Issue by jpcanip** [ibell/coolprop#237]
Trying to install Coolprop either by using easy_install (sudo easy_install CoolProp) or pip (pip install CoolProp)on Ubuntu12.04, I get the same error. The log for the easy_install procedure is pasted below. The log for thepip procedure shares common parts with the easy_install one : 
"git version 1.7.9.5
git was found
fatal: Not a git repository (or any of the parent directories): .git
tried to update git revision, but it failed for some reason (building from zip file?)"

and

"  File "setup.py", line 197, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 87, in **init**
    **kw)
TypeError: unbound method **init**() must be called with Extension instance as first argument (got Extension instance instead)"

Newcomer to Python and python module management procedures, I don't know how interpret these logs and to solve this problem. Would there be any help ?
Thanks
JPh Caniparoli

Here is the completeeasy_install log ;
Searching for Coolprop
Reading http://pypi.python.org/simple/Coolprop/
Best match: CoolProp 4.2.5
Downloading https://pypi.python.org/packages/source/C/CoolProp/CoolProp-4.2.5.zip#md5=ffa8e7d52cd6e87e0b5c30227d1c9b11
Processing CoolProp-4.2.5.zip
Running CoolProp-4.2.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eSnyj9/CoolProp-4.2.5/egg-dist-tmp-hklQYd
git version 1.7.9.5
git was found
fatal: Not a git repository (or any of the parent directories): .git
tried to update git revision, but it failed for some reason (building from zip file?)
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.24dev-r0', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1931, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1935, in <lambda>
    distclass=DistributionWithoutHelpCommands, *_kw
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 368, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 608, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 638, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 828, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1105, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1094, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 72, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 32, in <lambda>
    {'**file**':setup_script, '**name**':'**main**'}
  File "setup.py", line 197, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 87, in **init**
    *_kw)
TypeError: unbound method **init**() must be called with Extension instance as first argument (got Extension instance instead)

**Comment by ibell** [comment]
Weird.  Not seen that one before.  I think your Cython might be out of date.

What do you get for

python -c "import Cython; print Cython.**version**"

?

**Comment by jpcanip** [comment]
Hello,

Thanks for your very rapid answer ; the cython version I get is 0.20.2

JPh Caniparoli

**Comment by ibell** [comment]
Works for me on xubuntu 14.04.  How about updating your pip? Or distutils?  Something is a bit out of date it would seem. Suppose this could be a bug with Cython as well. But it definitely works for me.

What version of python are you using?

I use anaconda/miniconda on all platforms now, and I am extremely pleased.  I might recommend that if you are not too invested in another package manager.

**Comment by jpcanip** [comment]
Updating pip and setuptools solved the issue : I could install and run 
CoolProp (I'm using Spyder/Anaconda)

Thanks a lot for your work.

JPh Caniparoli

**Comment by ibell** [comment]
Cool, good to hear.
